// Built from tag v3.3.0-rc-1

using System;

namespace FINT.Model.Administrasjon.Kodeverk
{
	public enum KodeverkActions
    {
	
	GET_ANSVAR,
	GET_ALL_ANSVAR,
	UPDATE_ANSVAR,
	GET_ARBEIDSFORHOLDSTYPE,
	GET_ALL_ARBEIDSFORHOLDSTYPE,
	UPDATE_ARBEIDSFORHOLDSTYPE,
	GET_ART,
	GET_ALL_ART,
	UPDATE_ART,
	GET_FRAVARSGRUNN,
	GET_ALL_FRAVARSGRUNN,
	UPDATE_FRAVARSGRUNN,
	GET_FRAVARSTYPE,
	GET_ALL_FRAVARSTYPE,
	UPDATE_FRAVARSTYPE,
	GET_FUNKSJON,
	GET_ALL_FUNKSJON,
	UPDATE_FUNKSJON,
	GET_LONNSART,
	GET_ALL_LONNSART,
	UPDATE_LONNSART,
	GET_PERSONALRESSURSKATEGORI,
	GET_ALL_PERSONALRESSURSKATEGORI,
	UPDATE_PERSONALRESSURSKATEGORI,
	GET_PROSJEKT,
	GET_ALL_PROSJEKT,
	UPDATE_PROSJEKT,
	GET_STILLINGSKODE,
	GET_ALL_STILLINGSKODE,
	UPDATE_STILLINGSKODE,
	GET_UKETIMETALL,
	GET_ALL_UKETIMETALL,
	UPDATE_UKETIMETALL
    }
}
