// Built from tag v2.6.0-beta-2

using System;

namespace FINT.Model.Administrasjon.Personal
{
	public enum PersonalActions
    {
	
	GET_FASTLONN,
	GET_ALL_FASTLONN,
	UPDATE_FASTLONN,
	GET_VARIABELLONN,
	GET_ALL_VARIABELLONN,
	UPDATE_VARIABELLONN,
	GET_PERSONALRESSURS,
	GET_ALL_PERSONALRESSURS,
	UPDATE_PERSONALRESSURS,
	GET_ARBEIDSFORHOLD,
	GET_ALL_ARBEIDSFORHOLD,
	UPDATE_ARBEIDSFORHOLD
    }
}
